// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Model.EF;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace Model.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Model.RankingList", b =>
                {
                    b.Property<int>("RID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SendMessage")
                        .HasMaxLength(100);

                    b.Property<DateTime>("SendTime");

                    b.Property<string>("SenderIP")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("RID");

                    b.ToTable("RankingList");
                });
#pragma warning restore 612, 618
        }
    }
}
